spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jobdb
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # change to validate in production
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: "01234567890123456789012345678901" # 32+ chars = 256+ bits
  expiration: 3600000   # 1 hour

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
